### Find all users
GET http://localhost:8080/users

### Find user by id
GET http://localhost:8080/user/11

### Create user
POST http://localhost:8080/user
Content-Type: application/json

{
    "name":"Juan",
    "email":"nuevo15@gmail.com",
    "role":"01",
    "password":"secret"
}
### Update user
PUT http://localhost:8080/user/2
Content-Type: application/json

{
    "name":"Juan",
    "email":"17999@gmail.com",
    "role":"01",
    "password":"secret",
    "createdAt" : "2023-08-15T11:38:49.000Z",
    "updatedAt" : "2023-08-15T13:00:49.000Z"
}
### Delete user
DELETE http://localhost:8080/user/11
